# Domaći 2 - Uklanjanje distorzije

## Biblioteke

In [2]:
import numpy as np
import lib.pg_transform as pgt

## Testiranje funkcija

Ulazni podaci:

In [3]:
a = np.array([-3, -1, 1])
b = np.array([3, -1, 1])
c = np.array([1, 1, 1])
d = np.array([-1, 1, 1])

ap = np.array([-2, -1, 1])
bp = np.array([2, -1, 1])
cp = np.array([2, 1, 1])
dp = np.array([-2, 1, 1])

Testiranje naivnog algoritma:

In [4]:
P1 = pgt.naive(a, b, c, d, ap, bp, cp, dp)
print(P1)

[[ 2.00000000e+00 -6.66133815e-16  6.66133815e-16]
 [-4.44089210e-16  2.00000000e+00 -1.00000000e+00]
 [ 4.44089210e-16 -1.00000000e+00  2.00000000e+00]]


Testiranje DLT algoritma:

In [5]:
e = np.array([1, 2, 3])
f = np.array([-8, -2, 1])

ep = P1 @ e
fp = P1 @ f

P2 = pgt.dlt([a, b, c, d, e, f],
             [ap, bp, cp, dp, ep, fp])

print(P2)

[[-5.34522484e-01 -3.33066907e-16  1.56992475e-16]
 [-1.11022302e-16 -5.34522484e-01  2.67261242e-01]
 [ 1.38777878e-17  2.67261242e-01 -5.34522484e-01]]


Upoređivanje rezultata naivnog algoritma i DLT algoritma:

In [6]:
print(P2 / P2[0,0] * P1[0,0])

[[ 2.00000000e+00  1.24622225e-15 -5.87412052e-16]
 [ 4.15407418e-16  2.00000000e+00 -1.00000000e+00]
 [-5.19259273e-17 -1.00000000e+00  2.00000000e+00]]


Testiranje unapređenog DLT algoritma:

In [7]:
e = np.array([1, 2, 3])
f = np.array([-8, -2, 1])

ep = P1 @ e
fp = P1 @ f

P3 = pgt.dlt2([a, b, c, d, e, f], [ap, bp, cp, dp, ep, fp])

print(P3)

[[-4.00617380e-01 -2.49941696e-16  3.33066907e-16]
 [ 1.24655527e-18 -4.00617380e-01  2.00308690e-01]
 [-7.03250359e-17  2.00308690e-01 -4.00617380e-01]]


Upoređivanje rezultata naivnog algoritma i unapređenog DLT algorima:

In [8]:
print(P3 / P3[0][0] * P1[0][0])

[[ 2.00000000e+00  1.24778259e-15 -1.66276814e-15]
 [-6.22317121e-18  2.00000000e+00 -1.00000000e+00]
 [ 3.51083300e-16 -1.00000000e+00  2.00000000e+00]]


## Dodatni test primeri

In [10]:
y1 = np.array([2, 1, 1])
y2 = np.array([1, 2, 1])
y3 = np.array([3, 4, 1])
y4 = np.array([-1, -3, 1])
y5 = np.array([-2, 5, 1])

y1p = np.array([0, 1, 1])
y2p = np.array([5, 0, 1])
y3p = np.array([2, -5, 1])
y4p = np.array([-1, -1, 1])
y5p = np.array([4, 1, 1])

yn1 = np.array([0, -3, 1])
yn2 = np.array([0, -1, 1])
yn3 = np.array([4, -1, 1])
yn4 = np.array([-7, -4, 1])
yn5 = np.array([0, 5, 1])

yn1p = np.array([3, -1, 1])
yn2p = np.array([4, 4, 1])
yn3p = np.array([9, 1, 1])
yn4p = np.array([5, -2, 1])
yn5p = np.array([7, 2, 1])


### 1.

In [11]:
P4 = pgt.naive(y1, y2, y3, y4, y1p, y2p, y3p, y4p)
print(P4 / P4[0][0])

[[ 1.         -0.4893617  -1.5106383 ]
 [ 0.62765957 -0.04255319 -0.54255319]
 [ 0.5        -0.46808511  0.13829787]]


In [13]:
P5 = pgt.dlt([y1, y2, y3, y4], [y1p, y2p, y3p, y4p])
print(P5 / P5[0][0])

[[ 1.         -0.4893617  -1.5106383 ]
 [ 0.62765957 -0.04255319 -0.54255319]
 [ 0.5        -0.46808511  0.13829787]]


In [15]:
P6 = pgt.dlt([y1, y2, y3, y4], [y1p, y2p, y3p, y4p])
print(P6 / P6[0][0])

[[ 1.         -0.4893617  -1.5106383 ]
 [ 0.62765957 -0.04255319 -0.54255319]
 [ 0.5        -0.46808511  0.13829787]]


### 2.

In [17]:
P7 = pgt.dlt([y1, y2, y3, y4, y5], [y1p, y2p, y3p, y4p, y5p])
print(P7 / P7[0][0])

[[ 1.         -0.57023838 -1.11777168]
 [ 0.38516187 -0.09014103 -0.2550288 ]
 [ 0.23495976 -0.19419603 -0.06077942]]


In [18]:
P8 = pgt.dlt2([y1, y2, y3, y4, y5], [y1p, y2p, y3p, y4p, y5p])
print(P8 / P8[0][0])

[[ 1.         -0.57539637 -1.09716407]
 [ 0.3864266  -0.09380412 -0.24994768]
 [ 0.23626643 -0.19372759 -0.06361069]]


### 3.

In [21]:
P10 = pgt.dlt2([yn1, yn2, yn3, yn4, yn5], [yn1p, yn2p, yn3p, yn4p, yn5p])
print(P10 / P10[0][0])

[[  1.         -15.08413581 -32.50653449]
 [  1.68749387  -3.84886824 -12.77589295]
 [  0.09661447  -2.25813106  -4.265241  ]]
