# Domaći 03 - Izometrije

## Biblioteke

In [1]:
import numpy as np
from d03_rotacije import *

## Test primeri

In [2]:
n = 208
fi = (2 * np.pi / 6) * ((n % 5) + 1)
teta = (np.pi / 17) * ((n % 8) + 1) 
psi = (2 * np.pi / 8) * ((n % 7) + 1)
print(f"fi = {fi}")
print(f"teta = {teta}")
print(f"psi = {psi}")

fi = 4.1887902047863905
teta = 0.18479956785822313
psi = 4.71238898038469


### Euler2A

In [3]:
A1 = Euler2A(-np.arctan(0.25), -np.arcsin(8/9), np.arctan(4))
A1

array([[ 0.11111111, -0.88888889, -0.44444444],
       [ 0.44444444,  0.44444444, -0.77777778],
       [ 0.88888889, -0.11111111,  0.44444444]])

In [4]:
A2 = Euler2A(fi, teta, psi)
A2

array([[-1.80569229e-16, -5.00000000e-01,  8.66025404e-01],
       [-9.82973100e-01,  1.59131750e-01,  9.18747589e-02],
       [-1.83749518e-01, -8.51279676e-01, -4.91486550e-01]])

### AxisAngle

In [5]:
p1, fi1 = AxisAngle(A1)
print(f"p = {p1}")
print(f"f = {fi1}")

p = [ 0.33333333 -0.66666667  0.66666667]
f = 1.5707963267948966


In [6]:
p2, fi2 = AxisAngle(A2)
print(f"p = {p2}")
print(f"f = {fi2}")

p = [ 0.63231623 -0.70379748  0.32379822]
f = 3.9833175520834914


### Rodrigez

In [7]:
p1n = p1 / np.linalg.norm(p1)
A3 = Rodrigez(np.array([p1n]), fi1)
A3

array([[ 0.11111111, -0.88888889, -0.44444444],
       [ 0.44444444,  0.44444444, -0.77777778],
       [ 0.88888889, -0.11111111,  0.44444444]])

In [8]:
p2n = p2 / np.linalg.norm(p2)
A4 = Rodrigez(np.array([p2n]), fi2)
A4

array([[-1.66533454e-16, -5.00000000e-01,  8.66025404e-01],
       [-9.82973100e-01,  1.59131750e-01,  9.18747589e-02],
       [-1.83749518e-01, -8.51279676e-01, -4.91486550e-01]])

### A2Euler

In [9]:
fi1, teta1, psi1 = A2Euler(A3)
print(f"fi = {fi1}")
print(f"teta = {teta1}")
print(f"psi = {psi1}")

fi = -0.2449786631268642
teta = -1.09491407713448
psi = 1.3258176636680326


In [10]:
# Uglovi Fi i Psi su pomereni za 2*Pi
fi2, teta2, psi2 = A2Euler(A4)
print(f"fi = {fi2}")
print(f"teta = {teta2}")
print(f"psi = {psi2}")

fi = -2.094395102393196
teta = 0.18479956785822302
psi = -1.5707963267948968
